server:
  port: 7999
  error:
    include-message: Always

spring:
  application:
    name: play
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  profiles:
    active: ${PROFILE}